"""empty message

Revision ID: 56eadb49c283
Revises: 59a9cca10714
Create Date: 2023-04-18 18:28:32.414920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eadb49c283'
down_revision = '59a9cca10714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_transcripts')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('video_id')

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    op.create_table('_alembic_tmp_transcripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('json_string', sa.TEXT(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('video_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
