"""empty message

Revision ID: 572c4a5ab670
Revises: 0c8860b50f7e
Create Date: 2023-04-18 17:40:27.785971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572c4a5ab670'
down_revision = '0c8860b50f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('json_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('json_string',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
