"""empty message

Revision ID: 708e21d8692b
Revises: 3bca037f6cd1
Create Date: 2023-04-18 18:22:37.898958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708e21d8692b'
down_revision = '3bca037f6cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('video_id')

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
