"""empty message

Revision ID: c1815ee38ba7
Revises: d4a8c4cd99e4
Create Date: 2023-04-18 18:04:44.259155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1815ee38ba7'
down_revision = 'd4a8c4cd99e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('video_id')

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
