"""empty message

Revision ID: c4ca25dc0ed7
Revises: 609e8cbbb05f
Create Date: 2023-04-19 19:58:35.193155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ca25dc0ed7'
down_revision = '609e8cbbb05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snippet_thumbnails_maxres_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('snippet_thumbnails_maxres_url')

    # ### end Alembic commands ###
